-- 0004_force_rls.sql
-- Force RLS even for table owners (prevents "owner bypass")
-- This ensures RLS policies are enforced regardless of the DB role

-- Phase 0/1/2/3 tables
ALTER TABLE users FORCE ROW LEVEL SECURITY;
ALTER TABLE sessions FORCE ROW LEVEL SECURITY;
ALTER TABLE assets FORCE ROW LEVEL SECURITY;
ALTER TABLE label_templates FORCE ROW LEVEL SECURITY;
ALTER TABLE template_versions FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_logs FORCE ROW LEVEL SECURITY;
ALTER TABLE print_jobs FORCE ROW LEVEL SECURITY;
ALTER TABLE print_job_items FORCE ROW LEVEL SECURITY;

-- Phase 4 tables
ALTER TABLE api_keys FORCE ROW LEVEL SECURITY;
ALTER TABLE background_jobs FORCE ROW LEVEL SECURITY;
ALTER TABLE webhook_subscriptions FORCE ROW LEVEL SECURITY;
ALTER TABLE webhook_outbox FORCE ROW LEVEL SECURITY;
ALTER TABLE webhook_deliveries FORCE ROW LEVEL SECURITY;
ALTER TABLE import_templates FORCE ROW LEVEL SECURITY;
ALTER TABLE import_jobs FORCE ROW LEVEL SECURITY;
ALTER TABLE import_job_errors FORCE ROW LEVEL SECURITY;
ALTER TABLE export_jobs FORCE ROW LEVEL SECURITY;
ALTER TABLE print_agents FORCE ROW LEVEL SECURITY;
ALTER TABLE print_agent_printers FORCE ROW LEVEL SECURITY;
ALTER TABLE print_dispatches FORCE ROW LEVEL SECURITY;
ALTER TABLE cloud_print_providers FORCE ROW LEVEL SECURITY;
ALTER TABLE print_routes FORCE ROW LEVEL SECURITY;
